# Generated by Django 4.1.7 on 2024-06-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sslc', models.FileField(upload_to='')),
                ('plus_two', models.FileField(upload_to='')),
                ('degree', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='course_data',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='interview_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(max_length=250)),
                ('Qualification', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gmail', models.EmailField(max_length=250)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('payment_id', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Lock', 'Lock'), ('reject', 'reject'), ('Unlock', 'Unlock')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='placementreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('cv', models.FileField(upload_to='media')),
                ('position', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='trainer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('trainerphoto', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Userregistrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('Password', models.CharField(max_length=200, null=True)),
                ('user_photo', models.FileField(upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=250)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
